#index:
#    path: /
#    controller: App\Controller\DefaultController::index
page:
  type:     rest
  resource: App\Controller\PageController
  prefix:   /api

unknown:
  type:     rest
  resource: App\Controller\UnknownController
  prefix:   /api

french:
  type:     rest
  resource: App\Controller\FrenchController
  prefix:   /api